name: Deploy to Vercel

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: vercel-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write
  statuses: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      # Lấy cấu hình và env từ Vercel (tôn trọng ENV preview/production)
      - name: Vercel Pull
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          else
            vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
          fi

      # Build bằng Vercel (sử dụng script build trong package.json của Vite)
      - name: Vercel Build
        run: vercel build --token="$VERCEL_TOKEN"

      # Deploy Preview cho nhánh/PR khác main
      - name: Deploy Preview
        if: github.ref != 'refs/heads/main'
        run: vercel deploy --prebuilt --token="$VERCEL_TOKEN"

      # Deploy Production khi push vào main
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
